kind: ConfigMap
apiVersion: v1
metadata:
  name: tildy
  namespace: discord-bots
data:
  TLDBOTTO_MEMBERS_VOTE_NOT_REQUIRED: "${MEMBERS_VOTE_NOT_REQUIRED}"
  TLDBOTTO_TIMEZONES: "${TIMEZONES}"
  TLDBOTTO_MEAL_CONFIG: "${MEAL_CONFIG}"
  TLDBOTTO_NEXT_DAY_THRESHOLD: "${NEXT_DAY_THRESHOLD}"
  TLDBOTTO_DISABLED_FEATURES: "${DISABLED_FEATURES}"
  TLDBOTTO_AIRTABLE_BASE: "${TLDBOTTO_AIRTABLE_BASE}"
  SNAILEDIT_AIRTABLE_BASE: "${SNAILEDIT_AIRTABLE_BASE}"
  TLDBOTTO_SUPPORT_CHANNEL_ID: "${SUPPORT_CHANNEL_ID}"
  TLDBOTTO_SUPPORT_USER_IDS: "${SUPPORT_USER_IDS}"
  TLDBOTTO_ID: "Kubernetes-hosted TLDBotto"