apiVersion: apps/v1
kind: Deployment
metadata:
  name: tildy
  namespace: discord-bots
  labels:
    app.kubernetes.io/name: TLDBotto
    app.kubernetes.io/instance: Tildy
    app.kubernetes.io/version: ${TLDBOTTO_VERSION}
  annotations:
    operator.1password.io/item-path: "vaults/du4s3tc4ab7wnrijmb5fxjpbse/items/Tildy Credentials"
    operator.1password.io/item-name: "tildy-credentials"
    operator.1password.io/auto-restart: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: TLDBotto
      app.kubernetes.io/instance: Tildy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: TLDBotto
        app.kubernetes.io/instance: Tildy
        app.kubernetes.io/version: ${TLDBOTTO_VERSION}
    spec:
      containers:
      - name: bot
        image: ghcr.io/lovely-development-team/${IMAGE_NAME}:latest
        envFrom:
          - configMapRef:
              name: tildy
          - secretRef:
              name: tildy
        env:
          - name: LOG_TO_FILE
            value: "false"
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 100Mi